### ISSUE TITLE
Did this library support for JSON serialization or Hessian serialization?

### ISSUE THREAD

**Issue by alswl** [sofastack/sofa-bolt-python#3]
Did this library support for JSON serialization or Hessian serialization?

Another question, could this library communicate via sofa-rpc with backend server in Java?

**Comment by zhangdavids** [comment]
:clap:

**Comment by wanderxjtu** [comment]
1. only protobuf serialization is supported is this library.
2. Yes, if the server provides BOLT+protobuf interfaces.
