### ISSUE TITLE
在初始化AioClient的时候没有成功启动MeshClient

### ISSUE THREAD

**Issue by RongXiaoCong** [sofastack/sofa-bolt-python#4]
在本地搭了一个sofa-rpc服务端，诉求是通过python调用rpc接口，发现MeshClient没有成功启动报错，后面的订阅和调用自然是不可能成功的。请问一下为什么这里会去请求本地的13330接口，谢谢
![屏幕快照 2019-11-07 下午3 26 35](https://user-images.githubusercontent.com/44402034/68368804-c408cf80-0173-11ea-9a69-fb8b5adf6142.png)

**Comment by wanderxjtu** [comment]
`MeshClient` 连接的 13330 端口是 [sofa-mosn](https://github.com/sofastack/sofa-mosn) 提供的本地端口，目前是通过它连接到service mesh。
这不是一个强依赖，当sofa-mosn不可用时，需要通过本地静态的`SERVICE_MAP`来维护目标服务的地址。
